### ISSUE TITLE
Our CA gateways send no beacons

### ISSUE THREAD

**Issue by bfrk** [epics-extensions/ca-gateway#13]
The [manual](http://www.aps.anl.gov/epics/EpicsDocumentation/ExtensionsManuals/Gateway/Gateway.html#BeaconAnomalies) says: CA gateway sends beacons and also creates beacon anomalies when it comes up (and in certain other circumstances, too).

However, we do not see any beacons coming from CA gateways, none at all.

I tested this using using  `tcpdump 'udp port 5065'`, Götz uses a self-authored Python script.

**Comment by ralphlange** [comment]
Can you check the environment setting?
Setting ENV variables would be the only way I know to make the CA server *not* send beacons when it comes up.

**Comment by ralphlange** [comment]
Also the EPICS release would be interesting, as the CAS server is part of Base.

**Comment by goetzpf** [comment]
Hallo Ralph, 
we use the EPICS channel access gateway from debian packages, here are the versions:

`libepics3.14.12.3:amd64  3.14.12.3-11       amd64`
`epics-cagateway          2.0.6.0-1+zjessie  amd64`


the same behavior with these versions:
`libepics3.14.12.3:amd64            3.14.12.3-8                        amd64`
`epics-cagateway                    2.0.4.0-1                          amd64`

Environment variables whose names start with "EPICS":
`EPICS_CAS_INTF_ADDR_LIST=193.149.12.5 192.168.70.5`
`EPICS_CAS_ADDR_LIST=192.168.10.255 192.168.21.255 192.168.22.255 192.168.210.255 193.149.14.255 193.149.9.255 192.168.11.255 192.168.26.255 193.175.216.255 193.149.13.130 172.18.16.255 192.168.5.55 172.17.64.255 172.17.73.255 172.17.72.255 192.168.16.22`
`EPICS_CA_AUTO_ADDR_LIST=NO`
`EPICS_CA_ADDR_LIST=192.168.10.255 192.168.21.255 192.168.22.255 192.168.210.255 193.149.14.255 193.149.9.255 192.168.11.255 192.168.26.255 193.175.216.255 193.149.13.130 172.18.16.255 192.168.5.55 172.17.64.255 172.17.73.255 172.17.72.255 192.168.16.22`
`EPICS_CAS_IGNORE_ADDR_LIST=192.168.10.5 192.168.10.6 192.168.11.5 192.168.11.6 192.168.12.5 192.168.12.6 192.168.20.5 192.168.20.6 192.168.21.5 192.168.21.6 192.168.210.5 192.168.210.6 192.168.211.5 192.168.211.6 192.168.212.5 192.168.212.6 192.168.213.5 192.168.213.6 192.168.214.5 192.168.214.6 192.168.22.5 192.168.22.6 192.168.26.5 192.168.26.6 192.168.31.5 192.168.31.6 192.168.5.52 192.168.5.53 192.168.66.133 192.168.66.134 192.168.101.5 192.168.101.6 192.168.171.5 192.168.171.6 192.168.240.5 192.168.240.6 192.168.246.5 192.168.246.6 192.168.22.20 192.168.66.138 192.168.21.7 193.149.9.5 193.149.9.6 193.149.10.5 193.149.10.6 193.149.12.5 193.149.12.6 193.149.13.5 193.149.13.6 193.149.14.5 193.149.14.6 193.149.15.5 193.149.15.6 134.30.9.5 134.30.9.6 134.30.11.5 134.30.11.6 193.175.216.95 193.175.216.96 172.18.16.5 172.18.16.6 172.17.64.5 172.17.64.6 172.17.72.5 172.17.72.6 172.17.73.5 172.17.73.6 192.168.64.5 192.168.64.69 192.168.64.133 192.168.64.197 192.168.65.5 192.168.65.69 192.168.65.133 192.168.65.197 192.168.66.5 192.168.66.69 192.168.66.133 192.168.66.197 192.168.67.5 192.168.67.69 192.168.67.133 192.168.67.197 192.168.64.6 192.168.64.70 192.168.64.134 192.168.64.198 192.168.65.6 192.168.65.70 192.168.65.134 192.168.65.198 192.168.66.6 192.168.66.70 192.168.66.134 192.168.66.198 192.168.67.6 192.168.67.70 192.168.67.134 192.168.67.198 192.168.64.10 192.168.64.74 192.168.64.138 192.168.64.202 192.168.65.10 192.168.65.74 192.168.65.138 192.168.65.202 192.168.66.10 192.168.66.74 192.168.66.138 192.168.66.202 192.168.67.10 192.168.67.74 192.168.67.138 192.168.67.202 192.168.21.7 192.168.22.20`
`EPICS_CA_MAX_ARRAY_BYTES=26000000`

**Comment by ralphlange** [comment]
That really looks like a simple test case that is easy to reproduce.

**Comment by ralphlange** [comment]
Well,
After having looked at the CA documentation, especially the paragraph about [CA server configuration](http://www.aps.anl.gov/epics/base/R3-14/12-docs/CAref.html#Configurin2) I would think that you need to define `EPICS_CAS_BEACON_ADDR_LIST`.

**Comment by goetzpf** [comment]
It seems that setting EPICS_CAS_AUTO_BEACON_ADDR_LIST=YES does the trick. I verified that the gateway sends beacons when started with this option. It also generates a beacon anomaly when it is restarted. However, I wonder if it also produces beacon anomalies when one of it's connected CA servers or IOCs is restarted...

**Comment by ralphlange** [comment]
Note that this might send beacons on networks that the Gateway is not supposed to send beacons to, waking up clients and creating more name resolution traffic on networks that can't even reach it.

A Gateway should only send beacons on the networks that it offers PVs on, i.e. those on its  EPICS_CAS_INTF_ADDR_LIST.

**Comment by anjohnson** [comment]
Shouldn't the CAS default its beacon address auto list to be the set of broadcast addresses from the `EPICS_CAS_INTF_ADDR_LIST` anyway? I haven't checked...

**Comment by ralphlange** [comment]
That wold make sense - at least for the Gateway.

Remember that the default settings for the EPICS_CAS variables are taken from the EPICS_CA (client) side. This shows that these defaults were aimed at supporting IOCs to completely run in a separate CA domain by just setting EPICS_CA_ADDR_LIST. They actually do not make a lot of sense for the Gateway.

**Comment by bfrk** [comment]
I know that this is not the same issue but it is related: what about beacon anomalies from IOCs? Clients that monitor a PV via the gateway should get some kind of notification when a PV becomes available and re-send name resolution requests. Is this implemented in the gateway in some way? Götz said he couldn't see any beacon anomalies on the gateway's server side...

**Comment by ralphlange** [comment]
Yes, this is implemented.
When the Gateway sees anomaly on its inner side, it will "ring the bell" on the outer side to wake up its clients. (Jeff was even adding this functionality to CAS at that time.) Using yet another environment setting to limit the frequency of these additional wake-up calls.
This is not being covered by our (recently introduced and very preliminary) tests, though. Me wight have run into regression there.

**Comment by bfrk** [comment]
I am (belatedly) closing this ticket: every question has been answered and it seems to work with new enough version and appropriate environment settings. Thanks!
