### ISSUE TITLE
dynamically sized array subscriptions

### ISSUE THREAD

**Issue by bfrk** [epics-extensions/ca-gateway#16]
When I monitor an array PV via gateway I always get the maximum number of elements back. For instance, a waveform record with NELM=1000 and NORD=5 will give me 5 elements when requested directly (same subnet) but when the request goes via gateway I get 1000 elements back. Gateway version is 2.0.6 with base-3.14.12.3 (these are the versions that we can install as debian packages).

**Comment by ralphlange** [comment]
PCAS support for variable arrays has been added to the EPICS 3.14 release series through merge commit [`07434172`](https://git.launchpad.net/epics-base/commit/?h=3.14&id=07434172319922b287ce6277b89ce2e82bced3cb) with a fix for container GDDs in [`0f7f4710`](https://git.launchpad.net/epics-base/commit/?h=3.14&id=0f7f4710c6a6c9e8fe94c2527d050928405aa296), relased as part of base-3.14.12.6.

Using Base versions older than that, you will not be able to make use of the variable array size feature.

**Comment by bfrk** [comment]
Thanks, Ralph!
