### ISSUE TITLE
Gateway treats int/float values as hex

### ISSUE THREAD

**Issue by andrej-m** [epics-extensions/ca-gateway#37]
This is a followup to the tech-talk thread:
https://epics.anl.gov/tech-talk/2021/msg01394.php

When writing numeric values to a PV, Gateway will treat the input as hex if the value is followed by excess (non-digit) characters. This does not happen when writing directoy to an IOC.

If I caput to an IOC (no Gateway involved):
`$ EPICS_CA_ADDR_LIST=ioc_address caput x:ai 10extra`
or
`$ EPICS_CA_ADDR_LIST=ioc_address caput x:ai 10 extra`
The "extra" characters are ignored and the value 10 is stored in the record, which is OK.

Doing the same through CA Gateway:
`$ EPICS_CA_ADDR_LIST=gateway_address caput x:ai 10extra`
or
`$ EPICS_CA_ADDR_LIST=gateway_address caput x:ai 10 extra`
The "extra" characters at the end cause the record to store the value 16 (10 hex), which I don't expect.

The problem originated when an operator habitually added 'w' when caput-ing to a setpoint record controlling some output in Watts. In that case the `caput PS-Power 100w` resulted in PS-Power being set to 256 instead of the expected 100 (Watts).

I tried the change proposed by @anjohnson (thanks!) in his [tech-talk reply,](https://epics.anl.gov/tech-talk/2021/msg01397.php) substituting the call to epicsScanDouble() with sscanf() in [aitConvert.cc:getStringAsDouble()](https://github.com/epics-modules/pcas/blob/297fa347a97698ce9d6a5be7f4aeb5bdcc6d7241/src/gdd/aitConvert.cc#L53) and it seems to work: `caput x:ai 10w` stores 10 into the record, as expected. However I'm not sure if that will break any other functionality relying on the use of epicsScanDouble().

What's the best way to handle this issue?

Versions used:
OS: RHEL8
base-7.0.6
ca-gateway-2.1.2
pcas-4.13.2

**Comment by ralphlange** [comment]
Fixed when the Gateway is linked against PCAS >= 4.13.3 or Base 3.15 >= 3.15.10.
