### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by anjohnson** [epics-extensions/ca-gateway#8]
Suggestion: Rename `gateway.notes` to make it more visible and clear that it contains the release notes. It would probably work as a .md file too.

In the `testTop/README`, move the Python prerequisites higher up in the file to make them more visible too. This document could also mention that the version of Base used should be built with `SHARED_LIBRARIES=YES` since the pyepics module has to be able to find the libca.so (or the user could set the pyepics variable whose name escapes me to point to the `libca.so` in a different Base).

My earlier reported issue with the `nosetests --with-tap` command is moot, I have tap.py installed in my personal `PYTHONPATH` but was running these tests from a different account.

**Comment by ralphlange** [comment]
Good points. 
#9 outlines what more flexible tests could do.
